version: '3.7'
services:
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootprachigoel
      MYSQL_DATABASE: property_app
    ports:
      - "3306:3306"
